// source: proto/bot.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.yh_bot.Status', null, global);
goog.exportSymbol('proto.yh_bot.board', null, global);
goog.exportSymbol('proto.yh_bot.board.Board_data', null, global);
goog.exportSymbol('proto.yh_bot.board_send', null, global);
goog.exportSymbol('proto.yh_bot.bot_info', null, global);
goog.exportSymbol('proto.yh_bot.bot_info.Bot_data', null, global);
goog.exportSymbol('proto.yh_bot.bot_info_send', null, global);
goog.exportSymbol('proto.yh_bot.bot_stop_send', null, global);
goog.exportSymbol('proto.yh_bot.create_bot', null, global);
goog.exportSymbol('proto.yh_bot.create_bot.BotData', null, global);
goog.exportSymbol('proto.yh_bot.create_bot_send', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_bot.Status = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_bot.Status, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_bot.Status.displayName = 'proto.yh_bot.Status';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_bot.bot_info_send = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_bot.bot_info_send, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_bot.bot_info_send.displayName = 'proto.yh_bot.bot_info_send';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_bot.bot_info = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_bot.bot_info, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_bot.bot_info.displayName = 'proto.yh_bot.bot_info';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_bot.bot_info.Bot_data = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_bot.bot_info.Bot_data, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_bot.bot_info.Bot_data.displayName = 'proto.yh_bot.bot_info.Bot_data';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_bot.board_send = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_bot.board_send, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_bot.board_send.displayName = 'proto.yh_bot.board_send';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_bot.board = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.yh_bot.board.repeatedFields_, null);
};
goog.inherits(proto.yh_bot.board, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_bot.board.displayName = 'proto.yh_bot.board';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_bot.board.Board_data = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_bot.board.Board_data, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_bot.board.Board_data.displayName = 'proto.yh_bot.board.Board_data';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_bot.create_bot_send = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_bot.create_bot_send, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_bot.create_bot_send.displayName = 'proto.yh_bot.create_bot_send';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_bot.create_bot = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_bot.create_bot, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_bot.create_bot.displayName = 'proto.yh_bot.create_bot';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_bot.create_bot.BotData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_bot.create_bot.BotData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_bot.create_bot.BotData.displayName = 'proto.yh_bot.create_bot.BotData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_bot.bot_stop_send = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_bot.bot_stop_send, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_bot.bot_stop_send.displayName = 'proto.yh_bot.bot_stop_send';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_bot.Status.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_bot.Status.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_bot.Status} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.Status.toObject = function(includeInstance, msg) {
  var f, obj = {
requestId: jspb.Message.getFieldWithDefault(msg, 1, 0),
code: jspb.Message.getFieldWithDefault(msg, 2, 0),
msg: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_bot.Status}
 */
proto.yh_bot.Status.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_bot.Status;
  return proto.yh_bot.Status.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_bot.Status} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_bot.Status}
 */
proto.yh_bot.Status.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRequestId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCode(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_bot.Status.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_bot.Status.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_bot.Status} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.Status.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getCode();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getMsg();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int64 request_id = 1;
 * @return {number}
 */
proto.yh_bot.Status.prototype.getRequestId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.Status} returns this
 */
proto.yh_bot.Status.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 code = 2;
 * @return {number}
 */
proto.yh_bot.Status.prototype.getCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.Status} returns this
 */
proto.yh_bot.Status.prototype.setCode = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string msg = 3;
 * @return {string}
 */
proto.yh_bot.Status.prototype.getMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.Status} returns this
 */
proto.yh_bot.Status.prototype.setMsg = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_bot.bot_info_send.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_bot.bot_info_send.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_bot.bot_info_send} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.bot_info_send.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_bot.bot_info_send}
 */
proto.yh_bot.bot_info_send.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_bot.bot_info_send;
  return proto.yh_bot.bot_info_send.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_bot.bot_info_send} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_bot.bot_info_send}
 */
proto.yh_bot.bot_info_send.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_bot.bot_info_send.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_bot.bot_info_send.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_bot.bot_info_send} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.bot_info_send.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string id = 2;
 * @return {string}
 */
proto.yh_bot.bot_info_send.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.bot_info_send} returns this
 */
proto.yh_bot.bot_info_send.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_bot.bot_info.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_bot.bot_info.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_bot.bot_info} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.bot_info.toObject = function(includeInstance, msg) {
  var f, obj = {
status: (f = msg.getStatus()) && proto.yh_bot.Status.toObject(includeInstance, f),
data: (f = msg.getData()) && proto.yh_bot.bot_info.Bot_data.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_bot.bot_info}
 */
proto.yh_bot.bot_info.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_bot.bot_info;
  return proto.yh_bot.bot_info.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_bot.bot_info} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_bot.bot_info}
 */
proto.yh_bot.bot_info.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.yh_bot.Status;
      reader.readMessage(value,proto.yh_bot.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = new proto.yh_bot.bot_info.Bot_data;
      reader.readMessage(value,proto.yh_bot.bot_info.Bot_data.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_bot.bot_info.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_bot.bot_info.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_bot.bot_info} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.bot_info.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.yh_bot.Status.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.yh_bot.bot_info.Bot_data.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_bot.bot_info.Bot_data.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_bot.bot_info.Bot_data.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_bot.bot_info.Bot_data} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.bot_info.Bot_data.toObject = function(includeInstance, msg) {
  var f, obj = {
botId: jspb.Message.getFieldWithDefault(msg, 1, ""),
name: jspb.Message.getFieldWithDefault(msg, 2, ""),
nameId: jspb.Message.getFieldWithDefault(msg, 3, 0),
avatarUrl: jspb.Message.getFieldWithDefault(msg, 4, ""),
avatarId: jspb.Message.getFieldWithDefault(msg, 5, 0),
introduction: jspb.Message.getFieldWithDefault(msg, 6, ""),
createBy: jspb.Message.getFieldWithDefault(msg, 7, ""),
createTime: jspb.Message.getFieldWithDefault(msg, 8, 0),
headcount: jspb.Message.getFieldWithDefault(msg, 9, 0),
pb_private: jspb.Message.getFieldWithDefault(msg, 10, 0),
isStop: jspb.Message.getFieldWithDefault(msg, 11, 0),
alwaysAgree: jspb.Message.getFieldWithDefault(msg, 13, 0),
noDetele: jspb.Message.getFieldWithDefault(msg, 14, 0),
doNotDisturb: jspb.Message.getFieldWithDefault(msg, 15, 0),
top: jspb.Message.getFieldWithDefault(msg, 18, 0),
groupLimit: jspb.Message.getFieldWithDefault(msg, 20, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_bot.bot_info.Bot_data}
 */
proto.yh_bot.bot_info.Bot_data.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_bot.bot_info.Bot_data;
  return proto.yh_bot.bot_info.Bot_data.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_bot.bot_info.Bot_data} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_bot.bot_info.Bot_data}
 */
proto.yh_bot.bot_info.Bot_data.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBotId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNameId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAvatarUrl(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAvatarId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntroduction(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreateBy(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreateTime(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setHeadcount(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPrivate(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIsStop(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAlwaysAgree(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNoDetele(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDoNotDisturb(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTop(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGroupLimit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_bot.bot_info.Bot_data.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_bot.bot_info.Bot_data.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_bot.bot_info.Bot_data} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.bot_info.Bot_data.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBotId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getNameId();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getAvatarUrl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAvatarId();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getIntroduction();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCreateBy();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getCreateTime();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getHeadcount();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getPrivate();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getIsStop();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getAlwaysAgree();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = message.getNoDetele();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getDoNotDisturb();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
  f = message.getTop();
  if (f !== 0) {
    writer.writeInt32(
      18,
      f
    );
  }
  f = message.getGroupLimit();
  if (f !== 0) {
    writer.writeInt32(
      20,
      f
    );
  }
};


/**
 * optional string bot_id = 1;
 * @return {string}
 */
proto.yh_bot.bot_info.Bot_data.prototype.getBotId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.bot_info.Bot_data} returns this
 */
proto.yh_bot.bot_info.Bot_data.prototype.setBotId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.yh_bot.bot_info.Bot_data.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.bot_info.Bot_data} returns this
 */
proto.yh_bot.bot_info.Bot_data.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 name_id = 3;
 * @return {number}
 */
proto.yh_bot.bot_info.Bot_data.prototype.getNameId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.bot_info.Bot_data} returns this
 */
proto.yh_bot.bot_info.Bot_data.prototype.setNameId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string avatar_url = 4;
 * @return {string}
 */
proto.yh_bot.bot_info.Bot_data.prototype.getAvatarUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.bot_info.Bot_data} returns this
 */
proto.yh_bot.bot_info.Bot_data.prototype.setAvatarUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int64 avatar_id = 5;
 * @return {number}
 */
proto.yh_bot.bot_info.Bot_data.prototype.getAvatarId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.bot_info.Bot_data} returns this
 */
proto.yh_bot.bot_info.Bot_data.prototype.setAvatarId = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string introduction = 6;
 * @return {string}
 */
proto.yh_bot.bot_info.Bot_data.prototype.getIntroduction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.bot_info.Bot_data} returns this
 */
proto.yh_bot.bot_info.Bot_data.prototype.setIntroduction = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string create_by = 7;
 * @return {string}
 */
proto.yh_bot.bot_info.Bot_data.prototype.getCreateBy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.bot_info.Bot_data} returns this
 */
proto.yh_bot.bot_info.Bot_data.prototype.setCreateBy = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional int64 create_time = 8;
 * @return {number}
 */
proto.yh_bot.bot_info.Bot_data.prototype.getCreateTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.bot_info.Bot_data} returns this
 */
proto.yh_bot.bot_info.Bot_data.prototype.setCreateTime = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int64 headcount = 9;
 * @return {number}
 */
proto.yh_bot.bot_info.Bot_data.prototype.getHeadcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.bot_info.Bot_data} returns this
 */
proto.yh_bot.bot_info.Bot_data.prototype.setHeadcount = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 private = 10;
 * @return {number}
 */
proto.yh_bot.bot_info.Bot_data.prototype.getPrivate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.bot_info.Bot_data} returns this
 */
proto.yh_bot.bot_info.Bot_data.prototype.setPrivate = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int32 is_stop = 11;
 * @return {number}
 */
proto.yh_bot.bot_info.Bot_data.prototype.getIsStop = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.bot_info.Bot_data} returns this
 */
proto.yh_bot.bot_info.Bot_data.prototype.setIsStop = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int32 always_agree = 13;
 * @return {number}
 */
proto.yh_bot.bot_info.Bot_data.prototype.getAlwaysAgree = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.bot_info.Bot_data} returns this
 */
proto.yh_bot.bot_info.Bot_data.prototype.setAlwaysAgree = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional int32 no_detele = 14;
 * @return {number}
 */
proto.yh_bot.bot_info.Bot_data.prototype.getNoDetele = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.bot_info.Bot_data} returns this
 */
proto.yh_bot.bot_info.Bot_data.prototype.setNoDetele = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional int32 do_not_disturb = 15;
 * @return {number}
 */
proto.yh_bot.bot_info.Bot_data.prototype.getDoNotDisturb = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.bot_info.Bot_data} returns this
 */
proto.yh_bot.bot_info.Bot_data.prototype.setDoNotDisturb = function(value) {
  return jspb.Message.setProto3IntField(this, 15, value);
};


/**
 * optional int32 top = 18;
 * @return {number}
 */
proto.yh_bot.bot_info.Bot_data.prototype.getTop = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.bot_info.Bot_data} returns this
 */
proto.yh_bot.bot_info.Bot_data.prototype.setTop = function(value) {
  return jspb.Message.setProto3IntField(this, 18, value);
};


/**
 * optional int32 group_limit = 20;
 * @return {number}
 */
proto.yh_bot.bot_info.Bot_data.prototype.getGroupLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.bot_info.Bot_data} returns this
 */
proto.yh_bot.bot_info.Bot_data.prototype.setGroupLimit = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};


/**
 * optional Status status = 1;
 * @return {?proto.yh_bot.Status}
 */
proto.yh_bot.bot_info.prototype.getStatus = function() {
  return /** @type{?proto.yh_bot.Status} */ (
    jspb.Message.getWrapperField(this, proto.yh_bot.Status, 1));
};


/**
 * @param {?proto.yh_bot.Status|undefined} value
 * @return {!proto.yh_bot.bot_info} returns this
*/
proto.yh_bot.bot_info.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yh_bot.bot_info} returns this
 */
proto.yh_bot.bot_info.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yh_bot.bot_info.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Bot_data data = 2;
 * @return {?proto.yh_bot.bot_info.Bot_data}
 */
proto.yh_bot.bot_info.prototype.getData = function() {
  return /** @type{?proto.yh_bot.bot_info.Bot_data} */ (
    jspb.Message.getWrapperField(this, proto.yh_bot.bot_info.Bot_data, 2));
};


/**
 * @param {?proto.yh_bot.bot_info.Bot_data|undefined} value
 * @return {!proto.yh_bot.bot_info} returns this
*/
proto.yh_bot.bot_info.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yh_bot.bot_info} returns this
 */
proto.yh_bot.bot_info.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yh_bot.bot_info.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_bot.board_send.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_bot.board_send.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_bot.board_send} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.board_send.toObject = function(includeInstance, msg) {
  var f, obj = {
chatId: jspb.Message.getFieldWithDefault(msg, 3, ""),
chatType: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_bot.board_send}
 */
proto.yh_bot.board_send.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_bot.board_send;
  return proto.yh_bot.board_send.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_bot.board_send} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_bot.board_send}
 */
proto.yh_bot.board_send.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setChatId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setChatType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_bot.board_send.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_bot.board_send.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_bot.board_send} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.board_send.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChatId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getChatType();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional string chat_id = 3;
 * @return {string}
 */
proto.yh_bot.board_send.prototype.getChatId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.board_send} returns this
 */
proto.yh_bot.board_send.prototype.setChatId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 chat_type = 4;
 * @return {number}
 */
proto.yh_bot.board_send.prototype.getChatType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.board_send} returns this
 */
proto.yh_bot.board_send.prototype.setChatType = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.yh_bot.board.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_bot.board.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_bot.board.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_bot.board} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.board.toObject = function(includeInstance, msg) {
  var f, obj = {
status: (f = msg.getStatus()) && proto.yh_bot.Status.toObject(includeInstance, f),
boardList: jspb.Message.toObjectList(msg.getBoardList(),
    proto.yh_bot.board.Board_data.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_bot.board}
 */
proto.yh_bot.board.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_bot.board;
  return proto.yh_bot.board.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_bot.board} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_bot.board}
 */
proto.yh_bot.board.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.yh_bot.Status;
      reader.readMessage(value,proto.yh_bot.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = new proto.yh_bot.board.Board_data;
      reader.readMessage(value,proto.yh_bot.board.Board_data.deserializeBinaryFromReader);
      msg.addBoard(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_bot.board.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_bot.board.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_bot.board} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.board.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.yh_bot.Status.serializeBinaryToWriter
    );
  }
  f = message.getBoardList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.yh_bot.board.Board_data.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_bot.board.Board_data.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_bot.board.Board_data.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_bot.board.Board_data} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.board.Board_data.toObject = function(includeInstance, msg) {
  var f, obj = {
botId: jspb.Message.getFieldWithDefault(msg, 1, ""),
chatId: jspb.Message.getFieldWithDefault(msg, 2, ""),
chatType: jspb.Message.getFieldWithDefault(msg, 3, 0),
content: jspb.Message.getFieldWithDefault(msg, 4, ""),
contentType: jspb.Message.getFieldWithDefault(msg, 5, 0),
lastUpdateTime: jspb.Message.getFieldWithDefault(msg, 6, 0),
botName: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_bot.board.Board_data}
 */
proto.yh_bot.board.Board_data.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_bot.board.Board_data;
  return proto.yh_bot.board.Board_data.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_bot.board.Board_data} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_bot.board.Board_data}
 */
proto.yh_bot.board.Board_data.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBotId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setChatId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChatType(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setContentType(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLastUpdateTime(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setBotName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_bot.board.Board_data.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_bot.board.Board_data.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_bot.board.Board_data} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.board.Board_data.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBotId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getChatId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getChatType();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getContentType();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getLastUpdateTime();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getBotName();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string bot_id = 1;
 * @return {string}
 */
proto.yh_bot.board.Board_data.prototype.getBotId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.board.Board_data} returns this
 */
proto.yh_bot.board.Board_data.prototype.setBotId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string chat_id = 2;
 * @return {string}
 */
proto.yh_bot.board.Board_data.prototype.getChatId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.board.Board_data} returns this
 */
proto.yh_bot.board.Board_data.prototype.setChatId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 chat_type = 3;
 * @return {number}
 */
proto.yh_bot.board.Board_data.prototype.getChatType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.board.Board_data} returns this
 */
proto.yh_bot.board.Board_data.prototype.setChatType = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string content = 4;
 * @return {string}
 */
proto.yh_bot.board.Board_data.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.board.Board_data} returns this
 */
proto.yh_bot.board.Board_data.prototype.setContent = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 content_type = 5;
 * @return {number}
 */
proto.yh_bot.board.Board_data.prototype.getContentType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.board.Board_data} returns this
 */
proto.yh_bot.board.Board_data.prototype.setContentType = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 last_update_time = 6;
 * @return {number}
 */
proto.yh_bot.board.Board_data.prototype.getLastUpdateTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.board.Board_data} returns this
 */
proto.yh_bot.board.Board_data.prototype.setLastUpdateTime = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string bot_name = 7;
 * @return {string}
 */
proto.yh_bot.board.Board_data.prototype.getBotName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.board.Board_data} returns this
 */
proto.yh_bot.board.Board_data.prototype.setBotName = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional Status status = 1;
 * @return {?proto.yh_bot.Status}
 */
proto.yh_bot.board.prototype.getStatus = function() {
  return /** @type{?proto.yh_bot.Status} */ (
    jspb.Message.getWrapperField(this, proto.yh_bot.Status, 1));
};


/**
 * @param {?proto.yh_bot.Status|undefined} value
 * @return {!proto.yh_bot.board} returns this
*/
proto.yh_bot.board.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yh_bot.board} returns this
 */
proto.yh_bot.board.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yh_bot.board.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Board_data board = 2;
 * @return {!Array<!proto.yh_bot.board.Board_data>}
 */
proto.yh_bot.board.prototype.getBoardList = function() {
  return /** @type{!Array<!proto.yh_bot.board.Board_data>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.yh_bot.board.Board_data, 2));
};


/**
 * @param {!Array<!proto.yh_bot.board.Board_data>} value
 * @return {!proto.yh_bot.board} returns this
*/
proto.yh_bot.board.prototype.setBoardList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.yh_bot.board.Board_data=} opt_value
 * @param {number=} opt_index
 * @return {!proto.yh_bot.board.Board_data}
 */
proto.yh_bot.board.prototype.addBoard = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.yh_bot.board.Board_data, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.yh_bot.board} returns this
 */
proto.yh_bot.board.prototype.clearBoardList = function() {
  return this.setBoardList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_bot.create_bot_send.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_bot.create_bot_send.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_bot.create_bot_send} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.create_bot_send.toObject = function(includeInstance, msg) {
  var f, obj = {
name: jspb.Message.getFieldWithDefault(msg, 2, ""),
introduction: jspb.Message.getFieldWithDefault(msg, 3, ""),
avatarUrl: jspb.Message.getFieldWithDefault(msg, 4, ""),
pb_private: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_bot.create_bot_send}
 */
proto.yh_bot.create_bot_send.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_bot.create_bot_send;
  return proto.yh_bot.create_bot_send.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_bot.create_bot_send} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_bot.create_bot_send}
 */
proto.yh_bot.create_bot_send.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntroduction(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAvatarUrl(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPrivate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_bot.create_bot_send.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_bot.create_bot_send.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_bot.create_bot_send} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.create_bot_send.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getIntroduction();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAvatarUrl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPrivate();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.yh_bot.create_bot_send.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.create_bot_send} returns this
 */
proto.yh_bot.create_bot_send.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string introduction = 3;
 * @return {string}
 */
proto.yh_bot.create_bot_send.prototype.getIntroduction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.create_bot_send} returns this
 */
proto.yh_bot.create_bot_send.prototype.setIntroduction = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string avatar_url = 4;
 * @return {string}
 */
proto.yh_bot.create_bot_send.prototype.getAvatarUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.create_bot_send} returns this
 */
proto.yh_bot.create_bot_send.prototype.setAvatarUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 private = 5;
 * @return {number}
 */
proto.yh_bot.create_bot_send.prototype.getPrivate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.create_bot_send} returns this
 */
proto.yh_bot.create_bot_send.prototype.setPrivate = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_bot.create_bot.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_bot.create_bot.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_bot.create_bot} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.create_bot.toObject = function(includeInstance, msg) {
  var f, obj = {
status: (f = msg.getStatus()) && proto.yh_bot.Status.toObject(includeInstance, f),
data: (f = msg.getData()) && proto.yh_bot.create_bot.BotData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_bot.create_bot}
 */
proto.yh_bot.create_bot.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_bot.create_bot;
  return proto.yh_bot.create_bot.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_bot.create_bot} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_bot.create_bot}
 */
proto.yh_bot.create_bot.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.yh_bot.Status;
      reader.readMessage(value,proto.yh_bot.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = new proto.yh_bot.create_bot.BotData;
      reader.readMessage(value,proto.yh_bot.create_bot.BotData.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_bot.create_bot.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_bot.create_bot.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_bot.create_bot} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.create_bot.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.yh_bot.Status.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.yh_bot.create_bot.BotData.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_bot.create_bot.BotData.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_bot.create_bot.BotData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_bot.create_bot.BotData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.create_bot.BotData.toObject = function(includeInstance, msg) {
  var f, obj = {
botId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_bot.create_bot.BotData}
 */
proto.yh_bot.create_bot.BotData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_bot.create_bot.BotData;
  return proto.yh_bot.create_bot.BotData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_bot.create_bot.BotData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_bot.create_bot.BotData}
 */
proto.yh_bot.create_bot.BotData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBotId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_bot.create_bot.BotData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_bot.create_bot.BotData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_bot.create_bot.BotData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.create_bot.BotData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBotId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string bot_id = 1;
 * @return {string}
 */
proto.yh_bot.create_bot.BotData.prototype.getBotId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.create_bot.BotData} returns this
 */
proto.yh_bot.create_bot.BotData.prototype.setBotId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Status status = 1;
 * @return {?proto.yh_bot.Status}
 */
proto.yh_bot.create_bot.prototype.getStatus = function() {
  return /** @type{?proto.yh_bot.Status} */ (
    jspb.Message.getWrapperField(this, proto.yh_bot.Status, 1));
};


/**
 * @param {?proto.yh_bot.Status|undefined} value
 * @return {!proto.yh_bot.create_bot} returns this
*/
proto.yh_bot.create_bot.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yh_bot.create_bot} returns this
 */
proto.yh_bot.create_bot.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yh_bot.create_bot.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional BotData data = 2;
 * @return {?proto.yh_bot.create_bot.BotData}
 */
proto.yh_bot.create_bot.prototype.getData = function() {
  return /** @type{?proto.yh_bot.create_bot.BotData} */ (
    jspb.Message.getWrapperField(this, proto.yh_bot.create_bot.BotData, 2));
};


/**
 * @param {?proto.yh_bot.create_bot.BotData|undefined} value
 * @return {!proto.yh_bot.create_bot} returns this
*/
proto.yh_bot.create_bot.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yh_bot.create_bot} returns this
 */
proto.yh_bot.create_bot.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yh_bot.create_bot.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_bot.bot_stop_send.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_bot.bot_stop_send.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_bot.bot_stop_send} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.bot_stop_send.toObject = function(includeInstance, msg) {
  var f, obj = {
botId: jspb.Message.getFieldWithDefault(msg, 2, ""),
operation: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_bot.bot_stop_send}
 */
proto.yh_bot.bot_stop_send.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_bot.bot_stop_send;
  return proto.yh_bot.bot_stop_send.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_bot.bot_stop_send} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_bot.bot_stop_send}
 */
proto.yh_bot.bot_stop_send.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBotId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOperation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_bot.bot_stop_send.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_bot.bot_stop_send.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_bot.bot_stop_send} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_bot.bot_stop_send.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBotId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getOperation();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional string bot_id = 2;
 * @return {string}
 */
proto.yh_bot.bot_stop_send.prototype.getBotId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_bot.bot_stop_send} returns this
 */
proto.yh_bot.bot_stop_send.prototype.setBotId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 operation = 3;
 * @return {number}
 */
proto.yh_bot.bot_stop_send.prototype.getOperation = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_bot.bot_stop_send} returns this
 */
proto.yh_bot.bot_stop_send.prototype.setOperation = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


goog.object.extend(exports, proto.yh_bot);
