// source: proto/conversation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.yh_conversation.ConversationList', null, global);
goog.exportSymbol('proto.yh_conversation.ConversationList.ConversationData', null, global);
goog.exportSymbol('proto.yh_conversation.ConversationList.ConversationData.AtData', null, global);
goog.exportSymbol('proto.yh_conversation.Status', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_conversation.Status = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_conversation.Status, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_conversation.Status.displayName = 'proto.yh_conversation.Status';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_conversation.ConversationList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.yh_conversation.ConversationList.repeatedFields_, null);
};
goog.inherits(proto.yh_conversation.ConversationList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_conversation.ConversationList.displayName = 'proto.yh_conversation.ConversationList';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_conversation.ConversationList.ConversationData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_conversation.ConversationList.ConversationData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_conversation.ConversationList.ConversationData.displayName = 'proto.yh_conversation.ConversationList.ConversationData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_conversation.ConversationList.ConversationData.AtData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_conversation.ConversationList.ConversationData.AtData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_conversation.ConversationList.ConversationData.AtData.displayName = 'proto.yh_conversation.ConversationList.ConversationData.AtData';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_conversation.Status.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_conversation.Status.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_conversation.Status} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_conversation.Status.toObject = function(includeInstance, msg) {
  var f, obj = {
number: jspb.Message.getFieldWithDefault(msg, 1, 0),
code: jspb.Message.getFieldWithDefault(msg, 2, 0),
msg: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_conversation.Status}
 */
proto.yh_conversation.Status.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_conversation.Status;
  return proto.yh_conversation.Status.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_conversation.Status} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_conversation.Status}
 */
proto.yh_conversation.Status.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNumber(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCode(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_conversation.Status.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_conversation.Status.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_conversation.Status} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_conversation.Status.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNumber();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getCode();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getMsg();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int64 number = 1;
 * @return {number}
 */
proto.yh_conversation.Status.prototype.getNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_conversation.Status} returns this
 */
proto.yh_conversation.Status.prototype.setNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 code = 2;
 * @return {number}
 */
proto.yh_conversation.Status.prototype.getCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_conversation.Status} returns this
 */
proto.yh_conversation.Status.prototype.setCode = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string msg = 3;
 * @return {string}
 */
proto.yh_conversation.Status.prototype.getMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_conversation.Status} returns this
 */
proto.yh_conversation.Status.prototype.setMsg = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.yh_conversation.ConversationList.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_conversation.ConversationList.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_conversation.ConversationList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_conversation.ConversationList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_conversation.ConversationList.toObject = function(includeInstance, msg) {
  var f, obj = {
status: (f = msg.getStatus()) && proto.yh_conversation.Status.toObject(includeInstance, f),
dataList: jspb.Message.toObjectList(msg.getDataList(),
    proto.yh_conversation.ConversationList.ConversationData.toObject, includeInstance),
total: jspb.Message.getFieldWithDefault(msg, 3, 0),
requestId: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_conversation.ConversationList}
 */
proto.yh_conversation.ConversationList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_conversation.ConversationList;
  return proto.yh_conversation.ConversationList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_conversation.ConversationList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_conversation.ConversationList}
 */
proto.yh_conversation.ConversationList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.yh_conversation.Status;
      reader.readMessage(value,proto.yh_conversation.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = new proto.yh_conversation.ConversationList.ConversationData;
      reader.readMessage(value,proto.yh_conversation.ConversationList.ConversationData.deserializeBinaryFromReader);
      msg.addData(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotal(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_conversation.ConversationList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_conversation.ConversationList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_conversation.ConversationList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_conversation.ConversationList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.yh_conversation.Status.serializeBinaryToWriter
    );
  }
  f = message.getDataList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.yh_conversation.ConversationList.ConversationData.serializeBinaryToWriter
    );
  }
  f = message.getTotal();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_conversation.ConversationList.ConversationData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_conversation.ConversationList.ConversationData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_conversation.ConversationList.ConversationData.toObject = function(includeInstance, msg) {
  var f, obj = {
chatId: jspb.Message.getFieldWithDefault(msg, 1, ""),
chatType: jspb.Message.getFieldWithDefault(msg, 2, 0),
name: jspb.Message.getFieldWithDefault(msg, 3, ""),
chatContent: jspb.Message.getFieldWithDefault(msg, 4, ""),
timestampMs: jspb.Message.getFieldWithDefault(msg, 5, 0),
unreadMessage: jspb.Message.getFieldWithDefault(msg, 6, 0),
at: jspb.Message.getFieldWithDefault(msg, 7, 0),
avatarId: jspb.Message.getFieldWithDefault(msg, 8, 0),
avatarUrl: jspb.Message.getFieldWithDefault(msg, 9, ""),
doNotDisturb: jspb.Message.getFieldWithDefault(msg, 11, 0),
timestamp: jspb.Message.getFieldWithDefault(msg, 12, 0),
atData: (f = msg.getAtData()) && proto.yh_conversation.ConversationList.ConversationData.AtData.toObject(includeInstance, f),
certificationLevel: jspb.Message.getFieldWithDefault(msg, 16, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_conversation.ConversationList.ConversationData}
 */
proto.yh_conversation.ConversationList.ConversationData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_conversation.ConversationList.ConversationData;
  return proto.yh_conversation.ConversationList.ConversationData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_conversation.ConversationList.ConversationData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_conversation.ConversationList.ConversationData}
 */
proto.yh_conversation.ConversationList.ConversationData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setChatId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChatType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setChatContent(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestampMs(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUnreadMessage(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAt(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAvatarId(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setAvatarUrl(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDoNotDisturb(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 14:
      var value = new proto.yh_conversation.ConversationList.ConversationData.AtData;
      reader.readMessage(value,proto.yh_conversation.ConversationList.ConversationData.AtData.deserializeBinaryFromReader);
      msg.setAtData(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCertificationLevel(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_conversation.ConversationList.ConversationData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_conversation.ConversationList.ConversationData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_conversation.ConversationList.ConversationData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChatId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getChatType();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getChatContent();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getTimestampMs();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getUnreadMessage();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getAt();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getAvatarId();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getAvatarUrl();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getDoNotDisturb();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      12,
      f
    );
  }
  f = message.getAtData();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      proto.yh_conversation.ConversationList.ConversationData.AtData.serializeBinaryToWriter
    );
  }
  f = message.getCertificationLevel();
  if (f !== 0) {
    writer.writeInt32(
      16,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_conversation.ConversationList.ConversationData.AtData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_conversation.ConversationList.ConversationData.AtData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.toObject = function(includeInstance, msg) {
  var f, obj = {
unknown: jspb.Message.getFieldWithDefault(msg, 1, 0),
mentionedId: jspb.Message.getFieldWithDefault(msg, 2, ""),
mentionedName: jspb.Message.getFieldWithDefault(msg, 3, ""),
mentionedIn: jspb.Message.getFieldWithDefault(msg, 4, ""),
mentionerId: jspb.Message.getFieldWithDefault(msg, 6, ""),
mentionerName: jspb.Message.getFieldWithDefault(msg, 7, ""),
msgSeq: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_conversation.ConversationList.ConversationData.AtData}
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_conversation.ConversationList.ConversationData.AtData;
  return proto.yh_conversation.ConversationList.ConversationData.AtData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_conversation.ConversationList.ConversationData.AtData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_conversation.ConversationList.ConversationData.AtData}
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUnknown(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMentionedId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMentionedName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMentionedIn(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setMentionerId(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setMentionerName(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMsgSeq(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_conversation.ConversationList.ConversationData.AtData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_conversation.ConversationList.ConversationData.AtData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUnknown();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getMentionedId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMentionedName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMentionedIn();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMentionerId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getMentionerName();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getMsgSeq();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
};


/**
 * optional int64 unknown = 1;
 * @return {number}
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.prototype.getUnknown = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData.AtData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.prototype.setUnknown = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string mentioned_id = 2;
 * @return {string}
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.prototype.getMentionedId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData.AtData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.prototype.setMentionedId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string mentioned_name = 3;
 * @return {string}
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.prototype.getMentionedName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData.AtData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.prototype.setMentionedName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string mentioned_in = 4;
 * @return {string}
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.prototype.getMentionedIn = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData.AtData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.prototype.setMentionedIn = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string mentioner_id = 6;
 * @return {string}
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.prototype.getMentionerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData.AtData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.prototype.setMentionerId = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string mentioner_name = 7;
 * @return {string}
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.prototype.getMentionerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData.AtData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.prototype.setMentionerName = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional int64 msg_seq = 8;
 * @return {number}
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.prototype.getMsgSeq = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData.AtData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.AtData.prototype.setMsgSeq = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional string chat_id = 1;
 * @return {string}
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.getChatId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.setChatId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 chat_type = 2;
 * @return {number}
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.getChatType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.setChatType = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string chat_content = 4;
 * @return {string}
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.getChatContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.setChatContent = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int64 timestamp_ms = 5;
 * @return {number}
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.getTimestampMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.setTimestampMs = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 unread_message = 6;
 * @return {number}
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.getUnreadMessage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.setUnreadMessage = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 at = 7;
 * @return {number}
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.getAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.setAt = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int64 avatar_id = 8;
 * @return {number}
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.getAvatarId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.setAvatarId = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional string avatar_url = 9;
 * @return {string}
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.getAvatarUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.setAvatarUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional int32 do_not_disturb = 11;
 * @return {number}
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.getDoNotDisturb = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.setDoNotDisturb = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int64 timestamp = 12;
 * @return {number}
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional AtData at_data = 14;
 * @return {?proto.yh_conversation.ConversationList.ConversationData.AtData}
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.getAtData = function() {
  return /** @type{?proto.yh_conversation.ConversationList.ConversationData.AtData} */ (
    jspb.Message.getWrapperField(this, proto.yh_conversation.ConversationList.ConversationData.AtData, 14));
};


/**
 * @param {?proto.yh_conversation.ConversationList.ConversationData.AtData|undefined} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData} returns this
*/
proto.yh_conversation.ConversationList.ConversationData.prototype.setAtData = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yh_conversation.ConversationList.ConversationData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.clearAtData = function() {
  return this.setAtData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.hasAtData = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional int32 certification_level = 16;
 * @return {number}
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.getCertificationLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_conversation.ConversationList.ConversationData} returns this
 */
proto.yh_conversation.ConversationList.ConversationData.prototype.setCertificationLevel = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional Status status = 1;
 * @return {?proto.yh_conversation.Status}
 */
proto.yh_conversation.ConversationList.prototype.getStatus = function() {
  return /** @type{?proto.yh_conversation.Status} */ (
    jspb.Message.getWrapperField(this, proto.yh_conversation.Status, 1));
};


/**
 * @param {?proto.yh_conversation.Status|undefined} value
 * @return {!proto.yh_conversation.ConversationList} returns this
*/
proto.yh_conversation.ConversationList.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yh_conversation.ConversationList} returns this
 */
proto.yh_conversation.ConversationList.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yh_conversation.ConversationList.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated ConversationData data = 2;
 * @return {!Array<!proto.yh_conversation.ConversationList.ConversationData>}
 */
proto.yh_conversation.ConversationList.prototype.getDataList = function() {
  return /** @type{!Array<!proto.yh_conversation.ConversationList.ConversationData>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.yh_conversation.ConversationList.ConversationData, 2));
};


/**
 * @param {!Array<!proto.yh_conversation.ConversationList.ConversationData>} value
 * @return {!proto.yh_conversation.ConversationList} returns this
*/
proto.yh_conversation.ConversationList.prototype.setDataList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.yh_conversation.ConversationList.ConversationData=} opt_value
 * @param {number=} opt_index
 * @return {!proto.yh_conversation.ConversationList.ConversationData}
 */
proto.yh_conversation.ConversationList.prototype.addData = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.yh_conversation.ConversationList.ConversationData, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.yh_conversation.ConversationList} returns this
 */
proto.yh_conversation.ConversationList.prototype.clearDataList = function() {
  return this.setDataList([]);
};


/**
 * optional int32 total = 3;
 * @return {number}
 */
proto.yh_conversation.ConversationList.prototype.getTotal = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_conversation.ConversationList} returns this
 */
proto.yh_conversation.ConversationList.prototype.setTotal = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string request_id = 4;
 * @return {string}
 */
proto.yh_conversation.ConversationList.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_conversation.ConversationList} returns this
 */
proto.yh_conversation.ConversationList.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


goog.object.extend(exports, proto.yh_conversation);
