// source: proto/friend.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.yh_friend.Status', null, global);
goog.exportSymbol('proto.yh_friend.request_list', null, global);
goog.exportSymbol('proto.yh_friend.request_list.Request', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_friend.Status = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_friend.Status, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_friend.Status.displayName = 'proto.yh_friend.Status';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_friend.request_list = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.yh_friend.request_list.repeatedFields_, null);
};
goog.inherits(proto.yh_friend.request_list, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_friend.request_list.displayName = 'proto.yh_friend.request_list';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_friend.request_list.Request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_friend.request_list.Request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_friend.request_list.Request.displayName = 'proto.yh_friend.request_list.Request';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_friend.Status.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_friend.Status.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_friend.Status} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_friend.Status.toObject = function(includeInstance, msg) {
  var f, obj = {
number: jspb.Message.getFieldWithDefault(msg, 1, 0),
code: jspb.Message.getFieldWithDefault(msg, 2, 0),
msg: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_friend.Status}
 */
proto.yh_friend.Status.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_friend.Status;
  return proto.yh_friend.Status.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_friend.Status} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_friend.Status}
 */
proto.yh_friend.Status.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNumber(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCode(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_friend.Status.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_friend.Status.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_friend.Status} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_friend.Status.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNumber();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getCode();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getMsg();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int64 number = 1;
 * @return {number}
 */
proto.yh_friend.Status.prototype.getNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_friend.Status} returns this
 */
proto.yh_friend.Status.prototype.setNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 code = 2;
 * @return {number}
 */
proto.yh_friend.Status.prototype.getCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_friend.Status} returns this
 */
proto.yh_friend.Status.prototype.setCode = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string msg = 3;
 * @return {string}
 */
proto.yh_friend.Status.prototype.getMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_friend.Status} returns this
 */
proto.yh_friend.Status.prototype.setMsg = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.yh_friend.request_list.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_friend.request_list.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_friend.request_list.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_friend.request_list} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_friend.request_list.toObject = function(includeInstance, msg) {
  var f, obj = {
status: (f = msg.getStatus()) && proto.yh_friend.Status.toObject(includeInstance, f),
requestsList: jspb.Message.toObjectList(msg.getRequestsList(),
    proto.yh_friend.request_list.Request.toObject, includeInstance),
total: jspb.Message.getFieldWithDefault(msg, 3, 0),
pending: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_friend.request_list}
 */
proto.yh_friend.request_list.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_friend.request_list;
  return proto.yh_friend.request_list.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_friend.request_list} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_friend.request_list}
 */
proto.yh_friend.request_list.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.yh_friend.Status;
      reader.readMessage(value,proto.yh_friend.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = new proto.yh_friend.request_list.Request;
      reader.readMessage(value,proto.yh_friend.request_list.Request.deserializeBinaryFromReader);
      msg.addRequests(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotal(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPending(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_friend.request_list.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_friend.request_list.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_friend.request_list} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_friend.request_list.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.yh_friend.Status.serializeBinaryToWriter
    );
  }
  f = message.getRequestsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.yh_friend.request_list.Request.serializeBinaryToWriter
    );
  }
  f = message.getTotal();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getPending();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_friend.request_list.Request.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_friend.request_list.Request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_friend.request_list.Request} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_friend.request_list.Request.toObject = function(includeInstance, msg) {
  var f, obj = {
receivername: jspb.Message.getFieldWithDefault(msg, 1, ""),
receiveravatar: jspb.Message.getFieldWithDefault(msg, 2, ""),
name: jspb.Message.getFieldWithDefault(msg, 3, ""),
avatar: jspb.Message.getFieldWithDefault(msg, 4, ""),
groupname: jspb.Message.getFieldWithDefault(msg, 5, ""),
groupavatar: jspb.Message.getFieldWithDefault(msg, 6, ""),
inviterid: jspb.Message.getFieldWithDefault(msg, 7, ""),
sourcetype: jspb.Message.getFieldWithDefault(msg, 9, 0),
targettype: jspb.Message.getFieldWithDefault(msg, 10, 0),
targetid: jspb.Message.getFieldWithDefault(msg, 11, ""),
receiverid: jspb.Message.getFieldWithDefault(msg, 12, ""),
result: jspb.Message.getFieldWithDefault(msg, 13, 0),
processedat: jspb.Message.getFieldWithDefault(msg, 14, 0),
inviteat: jspb.Message.getFieldWithDefault(msg, 16, 0),
inviteatstr: jspb.Message.getFieldWithDefault(msg, 17, ""),
requestid: jspb.Message.getFieldWithDefault(msg, 18, 0),
botname: jspb.Message.getFieldWithDefault(msg, 19, ""),
botavatar: jspb.Message.getFieldWithDefault(msg, 20, ""),
processorname: jspb.Message.getFieldWithDefault(msg, 22, ""),
note: jspb.Message.getFieldWithDefault(msg, 23, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_friend.request_list.Request}
 */
proto.yh_friend.request_list.Request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_friend.request_list.Request;
  return proto.yh_friend.request_list.Request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_friend.request_list.Request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_friend.request_list.Request}
 */
proto.yh_friend.request_list.Request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setReceivername(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setReceiveravatar(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAvatar(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setGroupname(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setGroupavatar(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setInviterid(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSourcetype(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTargettype(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetid(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setReceiverid(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setResult(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setProcessedat(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setInviteat(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setInviteatstr(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRequestid(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setBotname(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setBotavatar(value);
      break;
    case 22:
      var value = /** @type {string} */ (reader.readString());
      msg.setProcessorname(value);
      break;
    case 23:
      var value = /** @type {string} */ (reader.readString());
      msg.setNote(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_friend.request_list.Request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_friend.request_list.Request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_friend.request_list.Request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_friend.request_list.Request.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReceivername();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getReceiveravatar();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAvatar();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getGroupname();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getGroupavatar();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getInviterid();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getSourcetype();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getTargettype();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getTargetid();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getReceiverid();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getResult();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = message.getProcessedat();
  if (f !== 0) {
    writer.writeInt64(
      14,
      f
    );
  }
  f = message.getInviteat();
  if (f !== 0) {
    writer.writeInt64(
      16,
      f
    );
  }
  f = message.getInviteatstr();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getRequestid();
  if (f !== 0) {
    writer.writeInt32(
      18,
      f
    );
  }
  f = message.getBotname();
  if (f.length > 0) {
    writer.writeString(
      19,
      f
    );
  }
  f = message.getBotavatar();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getProcessorname();
  if (f.length > 0) {
    writer.writeString(
      22,
      f
    );
  }
  f = message.getNote();
  if (f.length > 0) {
    writer.writeString(
      23,
      f
    );
  }
};


/**
 * optional string receiverName = 1;
 * @return {string}
 */
proto.yh_friend.request_list.Request.prototype.getReceivername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setReceivername = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string receiverAvatar = 2;
 * @return {string}
 */
proto.yh_friend.request_list.Request.prototype.getReceiveravatar = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setReceiveravatar = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.yh_friend.request_list.Request.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string avatar = 4;
 * @return {string}
 */
proto.yh_friend.request_list.Request.prototype.getAvatar = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setAvatar = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string groupName = 5;
 * @return {string}
 */
proto.yh_friend.request_list.Request.prototype.getGroupname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setGroupname = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string groupAvatar = 6;
 * @return {string}
 */
proto.yh_friend.request_list.Request.prototype.getGroupavatar = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setGroupavatar = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string inviterId = 7;
 * @return {string}
 */
proto.yh_friend.request_list.Request.prototype.getInviterid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setInviterid = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional int32 sourceType = 9;
 * @return {number}
 */
proto.yh_friend.request_list.Request.prototype.getSourcetype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setSourcetype = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 targetType = 10;
 * @return {number}
 */
proto.yh_friend.request_list.Request.prototype.getTargettype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setTargettype = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional string targetId = 11;
 * @return {string}
 */
proto.yh_friend.request_list.Request.prototype.getTargetid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setTargetid = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string receiverId = 12;
 * @return {string}
 */
proto.yh_friend.request_list.Request.prototype.getReceiverid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setReceiverid = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional int32 result = 13;
 * @return {number}
 */
proto.yh_friend.request_list.Request.prototype.getResult = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setResult = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional int64 processedAt = 14;
 * @return {number}
 */
proto.yh_friend.request_list.Request.prototype.getProcessedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setProcessedat = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional int64 inviteAt = 16;
 * @return {number}
 */
proto.yh_friend.request_list.Request.prototype.getInviteat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setInviteat = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional string inviteAtStr = 17;
 * @return {string}
 */
proto.yh_friend.request_list.Request.prototype.getInviteatstr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setInviteatstr = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional int32 requestId = 18;
 * @return {number}
 */
proto.yh_friend.request_list.Request.prototype.getRequestid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setRequestid = function(value) {
  return jspb.Message.setProto3IntField(this, 18, value);
};


/**
 * optional string botName = 19;
 * @return {string}
 */
proto.yh_friend.request_list.Request.prototype.getBotname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setBotname = function(value) {
  return jspb.Message.setProto3StringField(this, 19, value);
};


/**
 * optional string botAvatar = 20;
 * @return {string}
 */
proto.yh_friend.request_list.Request.prototype.getBotavatar = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setBotavatar = function(value) {
  return jspb.Message.setProto3StringField(this, 20, value);
};


/**
 * optional string processorName = 22;
 * @return {string}
 */
proto.yh_friend.request_list.Request.prototype.getProcessorname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 22, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setProcessorname = function(value) {
  return jspb.Message.setProto3StringField(this, 22, value);
};


/**
 * optional string note = 23;
 * @return {string}
 */
proto.yh_friend.request_list.Request.prototype.getNote = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 23, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_friend.request_list.Request} returns this
 */
proto.yh_friend.request_list.Request.prototype.setNote = function(value) {
  return jspb.Message.setProto3StringField(this, 23, value);
};


/**
 * optional Status status = 1;
 * @return {?proto.yh_friend.Status}
 */
proto.yh_friend.request_list.prototype.getStatus = function() {
  return /** @type{?proto.yh_friend.Status} */ (
    jspb.Message.getWrapperField(this, proto.yh_friend.Status, 1));
};


/**
 * @param {?proto.yh_friend.Status|undefined} value
 * @return {!proto.yh_friend.request_list} returns this
*/
proto.yh_friend.request_list.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yh_friend.request_list} returns this
 */
proto.yh_friend.request_list.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yh_friend.request_list.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Request requests = 2;
 * @return {!Array<!proto.yh_friend.request_list.Request>}
 */
proto.yh_friend.request_list.prototype.getRequestsList = function() {
  return /** @type{!Array<!proto.yh_friend.request_list.Request>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.yh_friend.request_list.Request, 2));
};


/**
 * @param {!Array<!proto.yh_friend.request_list.Request>} value
 * @return {!proto.yh_friend.request_list} returns this
*/
proto.yh_friend.request_list.prototype.setRequestsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.yh_friend.request_list.Request=} opt_value
 * @param {number=} opt_index
 * @return {!proto.yh_friend.request_list.Request}
 */
proto.yh_friend.request_list.prototype.addRequests = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.yh_friend.request_list.Request, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.yh_friend.request_list} returns this
 */
proto.yh_friend.request_list.prototype.clearRequestsList = function() {
  return this.setRequestsList([]);
};


/**
 * optional int32 total = 3;
 * @return {number}
 */
proto.yh_friend.request_list.prototype.getTotal = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_friend.request_list} returns this
 */
proto.yh_friend.request_list.prototype.setTotal = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 pending = 4;
 * @return {number}
 */
proto.yh_friend.request_list.prototype.getPending = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_friend.request_list} returns this
 */
proto.yh_friend.request_list.prototype.setPending = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


goog.object.extend(exports, proto.yh_friend);
