// source: proto/instruction.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.yh_instruction.Status', null, global);
goog.exportSymbol('proto.yh_instruction.get_bot_instruction', null, global);
goog.exportSymbol('proto.yh_instruction.instruction_list', null, global);
goog.exportSymbol('proto.yh_instruction.instruction_list.Data', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_instruction.get_bot_instruction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_instruction.get_bot_instruction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_instruction.get_bot_instruction.displayName = 'proto.yh_instruction.get_bot_instruction';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_instruction.Status = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_instruction.Status, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_instruction.Status.displayName = 'proto.yh_instruction.Status';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_instruction.instruction_list = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.yh_instruction.instruction_list.repeatedFields_, null);
};
goog.inherits(proto.yh_instruction.instruction_list, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_instruction.instruction_list.displayName = 'proto.yh_instruction.instruction_list';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yh_instruction.instruction_list.Data = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yh_instruction.instruction_list.Data, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yh_instruction.instruction_list.Data.displayName = 'proto.yh_instruction.instruction_list.Data';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_instruction.get_bot_instruction.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_instruction.get_bot_instruction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_instruction.get_bot_instruction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_instruction.get_bot_instruction.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_instruction.get_bot_instruction}
 */
proto.yh_instruction.get_bot_instruction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_instruction.get_bot_instruction;
  return proto.yh_instruction.get_bot_instruction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_instruction.get_bot_instruction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_instruction.get_bot_instruction}
 */
proto.yh_instruction.get_bot_instruction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_instruction.get_bot_instruction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_instruction.get_bot_instruction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_instruction.get_bot_instruction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_instruction.get_bot_instruction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string id = 3;
 * @return {string}
 */
proto.yh_instruction.get_bot_instruction.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_instruction.get_bot_instruction} returns this
 */
proto.yh_instruction.get_bot_instruction.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_instruction.Status.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_instruction.Status.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_instruction.Status} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_instruction.Status.toObject = function(includeInstance, msg) {
  var f, obj = {
number: jspb.Message.getFieldWithDefault(msg, 1, 0),
code: jspb.Message.getFieldWithDefault(msg, 2, 0),
msg: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_instruction.Status}
 */
proto.yh_instruction.Status.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_instruction.Status;
  return proto.yh_instruction.Status.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_instruction.Status} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_instruction.Status}
 */
proto.yh_instruction.Status.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setNumber(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCode(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_instruction.Status.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_instruction.Status.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_instruction.Status} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_instruction.Status.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNumber();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getCode();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getMsg();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional uint64 number = 1;
 * @return {number}
 */
proto.yh_instruction.Status.prototype.getNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_instruction.Status} returns this
 */
proto.yh_instruction.Status.prototype.setNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint64 code = 2;
 * @return {number}
 */
proto.yh_instruction.Status.prototype.getCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_instruction.Status} returns this
 */
proto.yh_instruction.Status.prototype.setCode = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string msg = 3;
 * @return {string}
 */
proto.yh_instruction.Status.prototype.getMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_instruction.Status} returns this
 */
proto.yh_instruction.Status.prototype.setMsg = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.yh_instruction.instruction_list.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_instruction.instruction_list.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_instruction.instruction_list.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_instruction.instruction_list} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_instruction.instruction_list.toObject = function(includeInstance, msg) {
  var f, obj = {
status: (f = msg.getStatus()) && proto.yh_instruction.Status.toObject(includeInstance, f),
dataList: jspb.Message.toObjectList(msg.getDataList(),
    proto.yh_instruction.instruction_list.Data.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_instruction.instruction_list}
 */
proto.yh_instruction.instruction_list.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_instruction.instruction_list;
  return proto.yh_instruction.instruction_list.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_instruction.instruction_list} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_instruction.instruction_list}
 */
proto.yh_instruction.instruction_list.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.yh_instruction.Status;
      reader.readMessage(value,proto.yh_instruction.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = new proto.yh_instruction.instruction_list.Data;
      reader.readMessage(value,proto.yh_instruction.instruction_list.Data.deserializeBinaryFromReader);
      msg.addData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_instruction.instruction_list.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_instruction.instruction_list.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_instruction.instruction_list} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_instruction.instruction_list.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.yh_instruction.Status.serializeBinaryToWriter
    );
  }
  f = message.getDataList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.yh_instruction.instruction_list.Data.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yh_instruction.instruction_list.Data.prototype.toObject = function(opt_includeInstance) {
  return proto.yh_instruction.instruction_list.Data.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yh_instruction.instruction_list.Data} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_instruction.instruction_list.Data.toObject = function(includeInstance, msg) {
  var f, obj = {
commandId: jspb.Message.getFieldWithDefault(msg, 1, 0),
botId: jspb.Message.getFieldWithDefault(msg, 2, ""),
commandName: jspb.Message.getFieldWithDefault(msg, 3, ""),
instructionType: jspb.Message.getFieldWithDefault(msg, 5, 0),
defaultText: jspb.Message.getFieldWithDefault(msg, 7, ""),
botSettingsJson: jspb.Message.getFieldWithDefault(msg, 10, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yh_instruction.instruction_list.Data}
 */
proto.yh_instruction.instruction_list.Data.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yh_instruction.instruction_list.Data;
  return proto.yh_instruction.instruction_list.Data.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yh_instruction.instruction_list.Data} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yh_instruction.instruction_list.Data}
 */
proto.yh_instruction.instruction_list.Data.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCommandId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBotId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCommandName(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setInstructionType(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setDefaultText(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setBotSettingsJson(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yh_instruction.instruction_list.Data.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yh_instruction.instruction_list.Data.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yh_instruction.instruction_list.Data} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yh_instruction.instruction_list.Data.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommandId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getBotId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCommandName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getInstructionType();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getDefaultText();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getBotSettingsJson();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * optional uint64 command_id = 1;
 * @return {number}
 */
proto.yh_instruction.instruction_list.Data.prototype.getCommandId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_instruction.instruction_list.Data} returns this
 */
proto.yh_instruction.instruction_list.Data.prototype.setCommandId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string bot_id = 2;
 * @return {string}
 */
proto.yh_instruction.instruction_list.Data.prototype.getBotId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_instruction.instruction_list.Data} returns this
 */
proto.yh_instruction.instruction_list.Data.prototype.setBotId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string command_name = 3;
 * @return {string}
 */
proto.yh_instruction.instruction_list.Data.prototype.getCommandName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_instruction.instruction_list.Data} returns this
 */
proto.yh_instruction.instruction_list.Data.prototype.setCommandName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint64 instruction_type = 5;
 * @return {number}
 */
proto.yh_instruction.instruction_list.Data.prototype.getInstructionType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.yh_instruction.instruction_list.Data} returns this
 */
proto.yh_instruction.instruction_list.Data.prototype.setInstructionType = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string default_text = 7;
 * @return {string}
 */
proto.yh_instruction.instruction_list.Data.prototype.getDefaultText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_instruction.instruction_list.Data} returns this
 */
proto.yh_instruction.instruction_list.Data.prototype.setDefaultText = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string bot_settings_json = 10;
 * @return {string}
 */
proto.yh_instruction.instruction_list.Data.prototype.getBotSettingsJson = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.yh_instruction.instruction_list.Data} returns this
 */
proto.yh_instruction.instruction_list.Data.prototype.setBotSettingsJson = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional Status status = 1;
 * @return {?proto.yh_instruction.Status}
 */
proto.yh_instruction.instruction_list.prototype.getStatus = function() {
  return /** @type{?proto.yh_instruction.Status} */ (
    jspb.Message.getWrapperField(this, proto.yh_instruction.Status, 1));
};


/**
 * @param {?proto.yh_instruction.Status|undefined} value
 * @return {!proto.yh_instruction.instruction_list} returns this
*/
proto.yh_instruction.instruction_list.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yh_instruction.instruction_list} returns this
 */
proto.yh_instruction.instruction_list.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yh_instruction.instruction_list.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Data data = 2;
 * @return {!Array<!proto.yh_instruction.instruction_list.Data>}
 */
proto.yh_instruction.instruction_list.prototype.getDataList = function() {
  return /** @type{!Array<!proto.yh_instruction.instruction_list.Data>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.yh_instruction.instruction_list.Data, 2));
};


/**
 * @param {!Array<!proto.yh_instruction.instruction_list.Data>} value
 * @return {!proto.yh_instruction.instruction_list} returns this
*/
proto.yh_instruction.instruction_list.prototype.setDataList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.yh_instruction.instruction_list.Data=} opt_value
 * @param {number=} opt_index
 * @return {!proto.yh_instruction.instruction_list.Data}
 */
proto.yh_instruction.instruction_list.prototype.addData = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.yh_instruction.instruction_list.Data, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.yh_instruction.instruction_list} returns this
 */
proto.yh_instruction.instruction_list.prototype.clearDataList = function() {
  return this.setDataList([]);
};


goog.object.extend(exports, proto.yh_instruction);
